# This is a basic workflow to help you get started with Actions

name: RTA_CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AUTOSAR_CP_BUILD:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run RTA AUTOSAR CP Build script
        working-directory: C:\AricWang\cd\
        run: cmd /c run_build.bat

      # Runs a set of commands using the runners shell
      - name: Upload S32G HEX bin file.
        working-directory: C:\AricWang\cd\
        run: |
          chdir
          echo '# Build Result 🚀' >> $GITHUB_STEP_SUMMARY
          echo '## Build Success 🚀' >> $GITHUB_STEP_SUMMARY
          echo '### S32G399A HEX bin has been generated. 🚀' >> $GITHUB_STEP_SUMMARY
          echo Update load hex bin done!
          
